Missing Data Handled using Pandas

In [1]:
!pip install numpy
!pip install pandas

Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.3.5)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import numpy as np
import pandas as pd

In [8]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [7]:
print(type(data))
print(type(df))

<class 'dict'>
<class 'pandas.DataFrame'>

In [10]:
print(df)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [14]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [ ]:

print(df.isna().sum())

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
df.isna().any()# Check if any column contains NaN values

A     True
B    False
C     True
D     True
dtype: bool

Removing missing Data

In [16]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [17]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
df.dropna(thresh=3) # Drop rows that have less than 3 non-NaN values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [19]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [20]:
values = {'A':0,'B':100,"C":300,'D':400}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [ ]:
df.fillna(df.mean()) # Fill NaN values with the mean of each column

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

Merging Joining and concatenation

In [2]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [3]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [4]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
pd.merge(employees,salaries) # By default, it performs an inner join, which means it will only include rows with matching employee_id in both DataFrames.

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [6]:
pd.merge(employees,salaries,on='employee_id',how ='inner') # Inner join: Only include rows with matching employee_id in both DataFrames.

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [7]:
pd.merge(employees,salaries,on='employee_id',how ='outer') # Outer join: Include all rows from both DataFrames, filling in NaN for missing matches.

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [8]:
pd.merge(employees,salaries,on='employee_id',how ='left') # Left join: Include all rows from the left DataFrame (employees) and matching rows from the right DataFrame (salaries). Fill in NaN for missing matches in the right DataFrame.

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [9]:
pd.merge(employees,salaries,on='employee_id',how ='right') # Right join: Include all rows from the right DataFrame (salaries) and matching rows from the left DataFrame (employees). Fill in NaN for missing matches in the left DataFrame.

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

Concatenation of 2 DataFrames

In [10]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [11]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [12]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1, df2]) # Concatenate df1 and df2 vertically (stacking rows). By default, it ignores the index and creates a new one.

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df2, df1])# Concatenate df2 and df1 vertically (stacking rows). By default, it ignores the index and creates a new one. The order of DataFrames in the list determines the order of rows in the resulting DataFrame.

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [15]:
pd.concat([df1,df2],axis=1) # Concatenate df1 and df2 horizontally (stacking columns). By default, it ignores the index and creates a new one. The order of DataFrames in the list determines the order of columns in the resulting DataFrame.

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

Joining 2 data frames

In [16]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [17]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [18]:
df2

   score
2     85
3     90
4     75

In [21]:
df1.join([df2],how="inner") # Join df1 and df2 based on their indices. By default, it performs a left join, which means it will include all rows from df1 and matching rows from df2. Fill in NaN for missing matches in df2.

      name  score
2      Bob     85
3  Charlie     90

In [22]:
df1.join([df2],how="outer")

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [23]:
df1.join([df2],how="left")

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [24]:
df2.join([df1],how="inner")

   score     name
2     85      Bob
3     90  Charlie